set serveroutput on
DECLARE
V_SNO STUDENT.STUDENTNO%TYPE;
V_SNAME VARCHAR2(40);
BEGIN
V_SNO := '&Enter_Student_No';
SELECT STUDENTNAME INTO V_SNAME FROM STUDENT WHERE STUDENTNO = V_SNO;
DBMS_OUTPUT.PUT_LINE ('Student number '||V_SNO||' is called '||V_SNAME||'.');
EXCEPTION
WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE ('There is no student with number '||V_SNO);
END;